import { tv } from 'tailwind-variants';

export const sizeStyles = tv({
  variants: {
    base: {
      xs: 'text-xs',
      sm: 'text-sm',
      caption: 'text-caption',
      base: 'text-base',
      lg: 'text-lg',
      xl: 'text-xl',
      '2xl': 'text-2xl',
      '3xl': 'text-3xl',
      '4xl': 'text-4xl',
      '5xl': 'text-5xl',
      '6xl': 'text-6xl',
      '7xl': 'text-7xl',
      '8xl': 'text-8xl',
      '9xl': 'text-9xl',
    },
    sm: {
      xs: 'sm:text-xs',
      sm: 'sm:text-sm',
      caption: 'sm:text-caption',
      base: 'sm:text-base',
      lg: 'sm:text-lg',
      xl: 'sm:text-xl',
      '2xl': 'sm:text-2xl',
      '3xl': 'sm:text-3xl',
      '4xl': 'sm:text-4xl',
      '5xl': 'sm:text-5xl',
      '6xl': 'sm:text-6xl',
      '7xl': 'sm:text-7xl',
      '8xl': 'sm:text-8xl',
      '9xl': 'sm:text-9xl',
    },
    md: {
      xs: 'md:text-xs',
      sm: 'md:text-sm',
      caption: 'md:text-caption',
      base: 'md:text-base',
      lg: 'md:text-lg',
      xl: 'md:text-xl',
      '2xl': 'md:text-2xl',
      '3xl': 'md:text-3xl',
      '4xl': 'md:text-4xl',
      '5xl': 'md:text-5xl',
      '6xl': 'md:text-6xl',
      '7xl': 'md:text-7xl',
      '8xl': 'md:text-8xl',
      '9xl': 'md:text-9xl',
    },
    lg: {
      xs: 'lg:text-xs',
      sm: 'lg:text-sm',
      caption: 'lg:text-caption',
      base: 'lg:text-base',
      lg: 'lg:text-lg',
      xl: 'lg:text-xl',
      '2xl': 'lg:text-2xl',
      '3xl': 'lg:text-3xl',
      '4xl': 'lg:text-4xl',
      '5xl': 'lg:text-5xl',
      '6xl': 'lg:text-6xl',
      '7xl': 'lg:text-7xl',
      '8xl': 'lg:text-8xl',
      '9xl': 'lg:text-9xl',
    },
    xl: {
      xs: 'xl:text-xs',
      sm: 'xl:text-sm',
      caption: 'xl:text-caption',
      base: 'xl:text-base',
      lg: 'xl:text-lg',
      xl: 'xl:text-xl',
      '2xl': 'xl:text-2xl',
      '3xl': 'xl:text-3xl',
      '4xl': 'xl:text-4xl',
      '5xl': 'xl:text-5xl',
      '6xl': 'xl:text-6xl',
      '7xl': 'xl:text-7xl',
      '8xl': 'xl:text-8xl',
      '9xl': 'xl:text-9xl',
    },
    '2xl': {
      xs: '2xl:text-xs',
      sm: '2xl:text-sm',
      caption: '2xl:text-caption',
      base: '2xl:text-base',
      lg: '2xl:text-lg',
      xl: '2xl:text-xl',
      '2xl': '2xl:text-2xl',
      '3xl': '2xl:text-3xl',
      '4xl': '2xl:text-4xl',
      '5xl': '2xl:text-5xl',
      '6xl': '2xl:text-6xl',
      '7xl': '2xl:text-7xl',
      '8xl': '2xl:text-8xl',
      '9xl': '2xl:text-9xl',
    },
  },
});

export const weightStyles = tv({
  variants: {
    base: {
      thin: 'font-thin',
      extralight: 'font-extralight',
      light: 'font-light',
      normal: 'font-normal',
      medium: 'font-medium',
      semibold: 'font-semibold',
      bold: 'font-bold',
      extrabold: 'font-extrabold',
      black: 'font-black',
    },
    sm: {
      thin: 'sm:font-thin',
      extralight: 'sm:font-extralight',
      light: 'sm:font-light',
      normal: 'sm:font-normal',
      medium: 'sm:font-medium',
      semibold: 'sm:font-semibold',
      bold: 'sm:font-bold',
      extrabold: 'sm:font-extrabold',
      black: 'sm:font-black',
    },
    md: {
      thin: 'md:font-thin',
      extralight: 'md:font-extralight',
      light: 'md:font-light',
      normal: 'md:font-normal',
      medium: 'md:font-medium',
      semibold: 'md:font-semibold',
      bold: 'md:font-bold',
      extrabold: 'md:font-extrabold',
      black: 'md:font-black',
    },
    lg: {
      thin: 'lg:font-thin',
      extralight: 'lg:font-extralight',
      light: 'lg:font-light',
      normal: 'lg:font-normal',
      medium: 'lg:font-medium',
      semibold: 'lg:font-semibold',
      bold: 'lg:font-bold',
      extrabold: 'lg:font-extrabold',
      black: 'lg:font-black',
    },
    xl: {
      thin: 'xl:font-thin',
      extralight: 'xl:font-extralight',
      light: 'xl:font-light',
      normal: 'xl:font-normal',
      medium: 'xl:font-medium',
      semibold: 'xl:font-semibold',
      bold: 'xl:font-bold',
      extrabold: 'xl:font-extrabold',
      black: 'xl:font-black',
    },
    '2xl': {
      thin: '2xl:font-thin',
      extralight: '2xl:font-extralight',
      light: '2xl:font-light',
      normal: '2xl:font-normal',
      medium: '2xl:font-medium',
      semibold: '2xl:font-semibold',
      bold: '2xl:font-bold',
      extrabold: '2xl:font-extrabold',
      black: '2xl:font-black',
    },
  },
});

export const leadingStyles = tv({
  variants: {
    base: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    sm: {
      none: 'sm:leading-none',
      tight: 'sm:leading-tight',
      snug: 'sm:leading-snug',
      normal: 'sm:leading-normal',
      relaxed: 'sm:leading-relaxed',
      loose: 'sm:leading-loose',
    },
    md: {
      none: 'md:leading-none',
      tight: 'md:leading-tight',
      snug: 'md:leading-snug',
      normal: 'md:leading-normal',
      relaxed: 'md:leading-relaxed',
      loose: 'md:leading-loose',
    },
    lg: {
      none: 'lg:leading-none',
      tight: 'lg:leading-tight',
      snug: 'lg:leading-snug',
      normal: 'lg:leading-normal',
      relaxed: 'lg:leading-relaxed',
      loose: 'lg:leading-loose',
    },
    xl: {
      none: 'xl:leading-none',
      tight: 'xl:leading-tight',
      snug: 'xl:leading-snug',
      normal: 'xl:leading-normal',
      relaxed: 'xl:leading-relaxed',
      loose: 'xl:leading-loose',
    },
    '2xl': {
      none: '2xl:leading-none',
      tight: '2xl:leading-tight',
      snug: '2xl:leading-snug',
      normal: '2xl:leading-normal',
      relaxed: '2xl:leading-relaxed',
      loose: '2xl:leading-loose',
    },
  },
});

export const alignStyles = tv({
  variants: {
    base: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
    sm: {
      left: 'sm:text-left',
      center: 'sm:text-center',
      right: 'sm:text-right',
      justify: 'sm:text-justify',
    },
    md: {
      left: 'md:text-left',
      center: 'md:text-center',
      right: 'md:text-right',
      justify: 'md:text-justify',
    },
    lg: {
      left: 'lg:text-left',
      center: 'lg:text-center',
      right: 'lg:text-right',
      justify: 'lg:text-justify',
    },
    xl: {
      left: 'xl:text-left',
      center: 'xl:text-center',
      right: 'xl:text-right',
      justify: 'xl:text-justify',
    },
    '2xl': {
      left: '2xl:text-left',
      center: '2xl:text-center',
      right: '2xl:text-right',
      justify: '2xl:text-justify',
    },
  },
});

export const italicStyles = tv({
  variants: { italic: { true: 'italic', false: 'not-italic' } },
});
